#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

exec 2> /home/pi/rc.local.log  # send stderr from rc.local to a log file
exec 1>&2                      # send stdout to the same log file
set -x                         # tell sh to display commands before execution

# Toggle for running Network test loop or not; set to 0 to disable
_NetworkTest=1

if [ "$_NetworkTest" != 0 ]; then
until [ $(hostname -I) ]
do
sleep 2
done
fi

# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

sleep 2

sudo python /home/pi/oratio/main.py -l quiet -u true &

(
until ping -nq -c3 8.8.8.8; do
   echo Waiting for network
   sleep 5
done
/usr/bin/ssh -o StrictHostKeychecking=no -t -t -l pi -R 9999:localhost:22 irvine@web619.webfaction.com &
echo $?
)

exit 0
